export const country = [
  { country: "Austria", iso2: "AT", phone_code: "+43", icon: "🇦🇹" },
  { country: "Belgium", iso2: "BE", phone_code: "+32", icon: "🇧🇪" },
  { country: "Bulgaria", iso2: "BG", phone_code: "+359", icon: "🇧🇬" },
  { country: "Croatia", iso2: "HR", phone_code: "+385", icon: "🇭🇷" },
  { country: "Cyprus", iso2: "CY", phone_code: "+357", icon: "🇨🇾" },
  { country: "Czech Republic", iso2: "CZ", phone_code: "+420", icon: "🇨🇿" },
  { country: "Denmark", iso2: "DK", phone_code: "+45", icon: "🇩🇰" },
  { country: "Estonia", iso2: "EE", phone_code: "+372", icon: "🇪🇪" },
  { country: "Finland", iso2: "FI", phone_code: "+358", icon: "🇫🇮" },
  { country: "France", iso2: "FR", phone_code: "+33", icon: "🇫🇷" },
  { country: "Germany", iso2: "DE", phone_code: "+49", icon: "🇩🇪" },
  { country: "Greece", iso2: "GR", phone_code: "+30", icon: "🇬🇷" },
  { country: "Hungary", iso2: "HU", phone_code: "+36", icon: "🇭🇺" },
  { country: "Iceland", iso2: "IS", phone_code: "+354", icon: "🇮🇸" },
  { country: "Ireland", iso2: "IE", phone_code: "+353", icon: "🇮🇪" },
  { country: "Italy", iso2: "IT", phone_code: "+39", icon: "🇮🇹" },
  { country: "Latvia", iso2: "LV", phone_code: "+371", icon: "🇱🇻" },
  { country: "Lithuania", iso2: "LT", phone_code: "+370", icon: "🇱🇹" },
  { country: "Luxembourg", iso2: "LU", phone_code: "+352", icon: "🇱🇺" },
  { country: "Malta", iso2: "MT", phone_code: "+356", icon: "🇲🇹" },
  { country: "Netherlands", iso2: "NL", phone_code: "+31", icon: "🇳🇱" },
  { country: "Norway", iso2: "NO", phone_code: "+47", icon: "🇳🇴" },
  { country: "Poland", iso2: "PL", phone_code: "+48", icon: "🇵🇱" },
  { country: "Portugal", iso2: "PT", phone_code: "+351", icon: "🇵🇹" },
  { country: "Romania", iso2: "RO", phone_code: "+40", icon: "🇷🇴" },
  { country: "Slovakia", iso2: "SK", phone_code: "+421", icon: "🇸🇰" },
  { country: "Slovenia", iso2: "SI", phone_code: "+386", icon: "🇸🇮" },
  { country: "Spain", iso2: "ES", phone_code: "+34", icon: "🇪🇸" },
  { country: "Sweden", iso2: "SE", phone_code: "+46", icon: "🇸🇪" },
  { country: "Switzerland", iso2: "CH", phone_code: "+41", icon: "🇨🇭" },
  { country: "United Kingdom", iso2: "GB", phone_code: "+44", icon: "🇬🇧" },
]
